<?php

namespace Database\Seeders;

use App\Models\Dependencia;
use DateTime;
use Illuminate\Database\Seeder;

class DependenciasSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $datenow = new DateTime();
        Dependencia::insert([
            ['vchNombreDependencia' => 'RECTORADO',
            'tstCreacionDependencia' => $datenow,
            'tstModificacionDependencia' => $datenow],
            ['vchNombreDependencia' => 'UNIDAD DE SECRETARIA GENERAL',
            'tstCreacionDependencia' => $datenow,
            'tstModificacionDependencia' => $datenow],
            ['vchNombreDependencia' => 'DIRECCIÓN ADMINISTRATIVA',
            'tstCreacionDependencia' => $datenow,
            'tstModificacionDependencia' => $datenow],
            ['vchNombreDependencia' => 'DEPARTAMENTO MANTENIMIENTO Y DESARROLLO FISICO',
            'tstCreacionDependencia' => $datenow,
            'tstModificacionDependencia' => $datenow],
            ['vchNombreDependencia' => 'CENTRO DE EDUCACION FISICA',
            'tstCreacionDependencia' => $datenow,
            'tstModificacionDependencia' => $datenow],
            ['vchNombreDependencia' => 'BIENESTAR POLITECNICO',
            'tstCreacionDependencia' => $datenow,
            'tstModificacionDependencia' => $datenow],
            ['vchNombreDependencia' => 'DIRECCIÓN DE VINCULACION COLECTIVIDAD',
            'tstCreacionDependencia' => $datenow,
            'tstModificacionDependencia' => $datenow],
            ['vchNombreDependencia' => 'AUDITORIO',
            'tstCreacionDependencia' => $datenow,
            'tstModificacionDependencia' => $datenow],
            ['vchNombreDependencia' => 'DIRECCIÓN FINANCIERA',
            'tstCreacionDependencia' => $datenow,
            'tstModificacionDependencia' => $datenow],
            ['vchNombreDependencia' => 'UNIDAD DE AUDITORIA INTERNA',
            'tstCreacionDependencia' => $datenow,
            'tstModificacionDependencia' => $datenow],
            ['vchNombreDependencia' => 'UNIDAD DE PROCURADURIA',
            'tstCreacionDependencia' => $datenow,
            'tstModificacionDependencia' => $datenow],
            ['vchNombreDependencia' => 'UNIDAD TECNICA DE PLANIFICACION',
            'tstCreacionDependencia' => $datenow,
            'tstModificacionDependencia' => $datenow],
            ['vchNombreDependencia' => 'UNIDAD DE DESARROLLO ACADEMICO',
            'tstCreacionDependencia' => $datenow,
            'tstModificacionDependencia' => $datenow],
            ['vchNombreDependencia' => 'UNIDAD TECNICA DE EVALUACION INTERNA',
            'tstCreacionDependencia' => $datenow,
            'tstModificacionDependencia' => $datenow],
            ['vchNombreDependencia' => 'DIRECCIÓN DE RELACIONES PÚBLICAS',
            'tstCreacionDependencia' => $datenow,
            'tstModificacionDependencia' => $datenow],
            ['vchNombreDependencia' => 'DIRECCIÓN DE PUBLICACIONES',
            'tstCreacionDependencia' => $datenow,
            'tstModificacionDependencia' => $datenow],
            ['vchNombreDependencia' => 'VICERRECTORADO ACADÉMICO',
            'tstCreacionDependencia' => $datenow,
            'tstModificacionDependencia' => $datenow],
            ['vchNombreDependencia' => 'CENTRO DE DOCUMENTACION',
            'tstCreacionDependencia' => $datenow,
            'tstModificacionDependencia' => $datenow],
            ['vchNombreDependencia' => 'SECRETARIA ACADEMICA',
            'tstCreacionDependencia' => $datenow,
            'tstModificacionDependencia' => $datenow],
            ['vchNombreDependencia' => 'UNIDAD DE ADMISIÓN Y NIVELACIÓN',
            'tstCreacionDependencia' => $datenow,
            'tstModificacionDependencia' => $datenow],
            ['vchNombreDependencia' => 'VICERRECTORADO DE INVESTIGACIÓN Y POSTGRADO',
            'tstCreacionDependencia' => $datenow,
            'tstModificacionDependencia' => $datenow],
            ['vchNombreDependencia' => 'INSTITUTO DE INVESTIGACIÓN',
            'tstCreacionDependencia' => $datenow,
            'tstModificacionDependencia' => $datenow],
            ['vchNombreDependencia' => 'INSTITUTO DE POSGRADO Y EDUCACIÓN CONTINUA',
            'tstCreacionDependencia' => $datenow,
            'tstModificacionDependencia' => $datenow],
            ['vchNombreDependencia' => 'VICERRECTORADO ADMINISTRATIVO',
            'tstCreacionDependencia' => $datenow,
            'tstModificacionDependencia' => $datenow],
            ['vchNombreDependencia' => 'DEPARTAMENTO DE TALENTO HUMANO',
            'tstCreacionDependencia' => $datenow,
            'tstModificacionDependencia' => $datenow],
            ['vchNombreDependencia' => 'CENTRO DE ATENCION INTEGRAL EN SALUD',
            'tstCreacionDependencia' => $datenow,
            'tstModificacionDependencia' => $datenow],
            ['vchNombreDependencia' => 'DIRECCIÓN DE TECNOLOGIAS DE LA INFORMACIÓN Y COMUNICACIÓN',
            'tstCreacionDependencia' => $datenow,
            'tstModificacionDependencia' => $datenow],
            ['vchNombreDependencia' => 'CENTRO DE IDIOMAS',
            'tstCreacionDependencia' => $datenow,
            'tstModificacionDependencia' => $datenow],
            ['vchNombreDependencia' => 'COOPERATIVA DE AHORRO Y CREDITO',
            'tstCreacionDependencia' => $datenow,
            'tstModificacionDependencia' => $datenow],
            ['vchNombreDependencia' => 'CLUB DE EMPLEADOS POLITÉCNICOS DE CHIMBORAZO',
            'tstCreacionDependencia' => $datenow,
            'tstModificacionDependencia' => $datenow],
            ['vchNombreDependencia' => 'UNIDAD DE SEGURIDAD',
            'tstCreacionDependencia' => $datenow,
            'tstModificacionDependencia' => $datenow],
            ['vchNombreDependencia' => 'SINDICATO DE TRABAJADORES',
            'tstCreacionDependencia' => $datenow,
            'tstModificacionDependencia' => $datenow],
            ['vchNombreDependencia' => 'FEDERACIÓN DE ESTUDIANTES POLITÉCNICOS DE CHIMBORAZO',
            'tstCreacionDependencia' => $datenow,
            'tstModificacionDependencia' => $datenow],
            ['vchNombreDependencia' => 'ASOCIACIÓN DE EMPLEADOS POLITÉCNICOS DE CHIMBORAZO',
            'tstCreacionDependencia' => $datenow,
            'tstModificacionDependencia' => $datenow],
            ['vchNombreDependencia' => 'ASOCIACIÓN DE PROFESORES POLITÉCNICOS DE CHIMBORAZO',
            'tstCreacionDependencia' => $datenow,
            'tstModificacionDependencia' => $datenow],
            ['vchNombreDependencia' => 'FACULTAD DE ADMINISTRACIÓN DE EMPRESAS',
            'tstCreacionDependencia' => $datenow,
            'tstModificacionDependencia' => $datenow],
            ['vchNombreDependencia' => 'FACULTAD DE CIENCIAS',
            'tstCreacionDependencia' => $datenow,
            'tstModificacionDependencia' => $datenow],
            ['vchNombreDependencia' => 'FACULTAD DE CIENCIAS PECUARIAS',
            'tstCreacionDependencia' => $datenow,
            'tstModificacionDependencia' => $datenow],
            ['vchNombreDependencia' => 'FACULTAD DE INFORMÁTICA Y ELECTRÓNICA',
            'tstCreacionDependencia' => $datenow,
            'tstModificacionDependencia' => $datenow],
            ['vchNombreDependencia' => 'FACULTAD DE RECURSOS NATURALES',
            'tstCreacionDependencia' => $datenow,
            'tstModificacionDependencia' => $datenow],
            ['vchNombreDependencia' => 'FACULTAD DE SALUD PÚBLICA',
            'tstCreacionDependencia' => $datenow,
            'tstModificacionDependencia' => $datenow],
            ['vchNombreDependencia' => 'FACULTAD DE MECÁNICA',
            'tstCreacionDependencia' => $datenow,
            'tstModificacionDependencia' => $datenow],
            ['vchNombreDependencia' => 'EXTENSIÓN MORONA SANTIAGO',
            'tstCreacionDependencia' => $datenow,
            'tstModificacionDependencia' => $datenow],
            ['vchNombreDependencia' => 'EXTENSIÓN NORTE AMAZÓNICA',
                'tstCreacionDependencia' => $datenow,
                    'tstModificacionDependencia' => $datenow]
        ]);
        
    }
}


